FROM node:16-alpine

WORKDIR /usr/src/app

COPY package*.json ./
COPY package-lock*.json ./

RUN npm install --force

COPY . .

EXPOSE 3030

ARG KERBB_BASE_URL

ENV KERBB_BASE_URL ${KERBB_BASE_URL}

CMD npm start